# Déploiement Kubernetes pour l'interface Streamlit
# Auteur: Dady Akrou Cyrille
# Email: cyrilledady0501@gmail.com

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  namespace: movie-recommendation
  labels:
    app: streamlit-ui
    component: frontend
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
        component: frontend
        version: v1.0.0
    spec:
      containers:
      - name: streamlit-ui
        image: movie-recommendation-streamlit:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
          name: http
          protocol: TCP
        env:
        - name: API_BASE_URL
          value: "http://recommendation-api-service:8000"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: recommendation-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui-service
  namespace: movie-recommendation
  labels:
    app: streamlit-ui
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: streamlit-ui

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui-nodeport
  namespace: movie-recommendation
  labels:
    app: streamlit-ui
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30851
    protocol: TCP
    name: http
  selector:
    app: streamlit-ui